---
- hosts: "{{ passed_in_hosts }}"
  gather_facts: true
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: update host
      yum: name=* state=latest
  
    - name: install epel
      shell: sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

    - name: install packages
      yum:
        name:
          - wget
          - nano
          - ansible
          - mariadb

    - name: copy roles
      unarchive:
        src: ansible/roles.tar.gz
        dest: /home/ec2-user/