---
#Copy configuration files

# - name: Copy httpd configuration file
#   copy: src=files/httpd.original dest=/etc/httpd/conf/httpd.conf

- name: Copy wordpress configuration file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
  notify:
   - restart apache
   - start Mariadb

- name: Copy wordpress configuration file
  copy: src=files/mariadb-server.cnf dest=/etc/my.cnf.d/
  notify:
   - restart Mariadb